### ISSUE TITLE
Run on python 3.5

### ISSUE THREAD

**Issue by Condorello** [newAM/hisensetv#1]
Hi, i'm trying to run on Python 3.5 on my raspberry but got this:

`i@raspberrypi:~ $ ./hisensetv/hisensetv.py -h
  File "./hisensetv/hisensetv.py", line 54
    f"you must be connected to call {func.__name__}"
                                                   ^
SyntaxError: invalid syntax
pi@raspberrypi:~ $ nano hisensetv/hisensetv.py 
pi@raspberrypi:~ $ ./hisensetv/hisensetv.py -h
  File "./hisensetv/hisensetv.py", line 88
    ):
    ^
`

after removed the 'f' i have error on line 88. Any advice? Thanks!

**Comment by newAM** [comment]
Try using python3.6, 3.7, or 3.8.

The "f-strings" are a feature in python 3.6 and newer.  I'll open a PR later to update the docs for this.

**Comment by newAM** [comment]
Added requirements to readme: https://github.com/newAM/hisensetv#requirements
