### ISSUE TITLE
How do you use this with home-assistant?

### ISSUE THREAD

**Issue by davebeiler** [newAM/hisensetv#16]
I was able to connect it and get a code from the TV

 davidbeiler@Davids-Air  ~/Downloads/hisensetv-master  hisensetv 192.168.1.202 --authorize                 1 ↵  1075  20:33:21
Please enter the 4-digit code: 3669
 davidbeiler@Davids-Air  ~/Downloads/hisensetv-master  hisensetv 192.168.1.202 --get volume                  ✔  1075  20:33:28
[2021-06-20 20:33:53,587] [INFO    ] volume: {
    "volume_type": 0,
    "volume_value": 0
}
 davidbeiler@Davids-Air  ~/Downloads/hisensetv-master                                                        ✔  1076  20:33:53

**Comment by newAM** [comment]
This package on its own is not enough to connect to homeassistant without additional code.

I used to maintain a component here: https://github.com/newAM/hisensetv_hass

I no longer maintain that; but it looks like there are some active forks.
