### ISSUE TITLE
Turn on the TV on "--key power"

### ISSUE THREAD

**Issue by nonvegan** [newAM/hisensetv#17]
Right now the paho connection just times out when the tv is turned off. We should send a wake-on-lan magic packet when this happens, turning on the TV. I've tested it with [wakeonlan](https://github.com/remcohaszing/pywakeonlan) and it does work on port 4343.

**Comment by newAM** [comment]
This one was intentional :)

There are multiple ways to wake up the TV from power off, I found that HDMI-CEC was effective for my usecase because it can detect if the TV is on or off faster than waiting for a socket to time out.  I did not want to include this as default behavior incase someone wanted to use a different power-on mechanism to handle this.

**Comment by nonvegan** [comment]
Yeah I figured you would leave it for other people to choose. I'm not sure which approach the remote app uses but it seems to also work pretty reliably. Could you please provide an example on how you did this?

**Comment by newAM** [comment]
I went a little bit crazy trying to find a reliable solution :sweat_smile:

Here is what I have tried:

* Wake on LAN
  * My TV dropped the Ethernet connection sometimes, and it required a manual unplug/replug to fix.
  * As you have noted it is also difficult to detect TV state with this approach.
  * Requires annoying network configuration to isolate the TV from the rest of my network (the security of this TV is poor).
* IR blasters
  * Work great, but this TV does not have an "off" or "on" IR command, just a "toggle power".
  * I used this with a TP link smart plug to power monitor to determine if the TV was on / off, unfortunately TP link switches are unreliable, and TP link stopped supporting local control of their products.
* Service port
  * There is a serial service port on this TV, but I was not able to get it to do anything useful.
* HDMI-CEC via a raspberry pi
  * `libcec` has a number of bugs and often segfaulted.
  * I was looking into fixing `libcec`, but the hardware is broadcom, and broadcom is notorious for bad documentation (see: https://github.com/hlandau/ortega/blob/b6e9aa384951d17b3b19c96328a311d1c1485c81/rtg-spec.md#fucking-broadcom).
* HDMI-CEC via custom micro-controller
  * The current working solution.

I have a micro-controller gaffer taped on to the back of my TV that accepts commands from my home theater PC.  The microcontroller is wired into the HDMI-CEC line on a free HDMI port.  Zero reliability issues so far, and I have full control over the hardware & firmware to fix it if something does go wrong.  Unfortunately this is crazy amounts of custom for what amounts to a power switch :expressionless: 

That all said if you want to do the same the code for this is open source:
Firmware: https://github.com/newAM/hdmi-cec-ctrl
CEC driver: https://github.com/newAM/stm32-cec

**Comment by nonvegan** [comment]
Thank you so much for your answer. Since the TV is right by my computer I just have two bat scripts on my desktop to either turn it on or off, not perfect but it will suffice for now 😅. HDMI-CEC seems like something that would be fun to dig into though 😃
