### ISSUE TITLE
class Hisense is duplicated

### ISSUE THREAD

**Issue by ejonesnospam** [newAM/hisensetv#2]
The definition for class Hisense is duplicated in both files '__init__.py' and 'hisensetv.py'.

Unfortunately the updates for volume up/down and ok send keys, was ineffective because the class import used appears to be utilized from  '__init__.py'.

2 Recommended Options -
1) If duplication is desired, please incorporate updates for volume up/down into '__init__.py'  as well.
2) If code reduction is desired, I believe the following can be added to 'hisensetv.py'. Then the class Hisense can be removed from 'hisensetv.py' and replace the same definition in '__init__.py'

from . import HisenseTv

**Comment by newAM** [comment]
Oof, that's bone headed mistake on my part, I will remove the hisense.py copy.

**Comment by newAM** [comment]
Fixed in 163635c3713fa066325b702980a514deda71ea9b
