### ISSUE TITLE
other keys

### ISSUE THREAD

**Issue by theRemoter** [newAM/hisensetv#7]
Hello

what about other keys on the remote? like channel numbers etc.?
how can I get the full api?

thanks!

**Comment by newAM** [comment]
I do not know if the other keys are available by the API (the app always crashes on my phone).

Feel free to open a pull-request if it is possible!

**Comment by theRemoter** [comment]
but what are the payload of the other keys? for example, I can see the for power it's "KEY_POWER", for the numbers what is the payload? home, settings, channels etc? where can we find them

**Comment by newAM** [comment]
I believe people have been connecting to the TV with the phone app and using wireshark or `mosquitto_sub` to view the commands as they are transmitted.

**Comment by JulianStremel** [comment]
i have updatet the code to launch youtube / amazonprime and netflix and also added the ability to change channels

**Comment by newAM** [comment]
Added in 0.2.0 thanks to @JulianStremel
