### ISSUE TITLE
I would like to open another experimental branch with added features

### ISSUE THREAD

**Issue by JulianStremel** [newAM/hisensetv#8]
this is my experimental updatet version with netflix/amazonprime/youtube support 
as well as switchable inputs and extended keys (ok/play/pause/fast_forward/etc.)

[hisensetv.zip](https://github.com/newAM/hisensetv/files/5762885/hisensetv.zip)

**Comment by newAM** [comment]
You can open a pull-request to do that: [docs](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

For public repositories on github people make pull-requests from branches on their own [fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks) of the repository, to prevent permissions issues.

**Comment by JulianStremel** [comment]
thanks a lot i am quite new to github
